# import shutil

#--------------------------------------------------------------

my_chdir("./uw_tmp")

# my_rm( ["LOG"] )
# 
# my_mv( "../LOG",  "LOG" )

xsys("quartus_sh -t uw-chip-synth-quartus.tcl kirsch_top")

# must use verilog here.
# vhdl netlist generated by precision contains libraries that
# quartus doesn't know about (e.g. fiftyfivenm.fiftyfivenm_components
my_print("    INFO: map... ")
xsys( "quartus_map kirsch_top --source kirsch_top_logic.v" )

my_print("fit... ")
xsys( "quartus_fit kirsch_top --effort=fast")

my_print("tan... ")
# xsys( "quartus_tan kirsch_top" )
xsys( "quartus_sta -t uw-chip-synth-quartus-timing.tcl kirsch_top" )

my_print( "asm... ")
xsys( "quartus_asm kirsch_top" )

my_println( "eda..." )
xsys( "quartus_eda kirsch_top --simulation --tool=modelsim --format=vhdl")
xsys( "quartus_eda kirsch_top --simulation --tool=modelsim --format=verilog")


# my_mv( "LOG", "../LOG" )
my_chdir( ".." )

my_mv( "uw_tmp/simulation/modelsim/kirsch_top.vo"       , "uw_tmp/kirsch_top_chip.v" )
my_mv( "uw_tmp/simulation/modelsim/kirsch_top.vho"       , "uw_tmp/kirsch_top_chip.vhd" )
my_mv( "uw_tmp/simulation/modelsim/kirsch_top_vhd.sdo" , "uw_tmp/kirsch_top_chip.sdf", no_warn=True )
my_mv( "uw_tmp/kirsch_top.sof" , "kirsch_top.sof" )

my_cp( "uw_tmp/kirsch_top.map.rpt", "RPT/area_chip.rpt", error_level=1 )
my_cp( "uw_tmp/timing_chip.rpt", "RPT/timing_chip.rpt", error_level=1 )
my_cp( "uw_tmp/timing_chip_path.rpt", "RPT/timing_chip_path.rpt", error_level=1 )

#------------------------------------------------------------------------
# build shim architecture

xsys( "uw-shim kirsch_top CHIP_MODE lstep  util.vhd mem.vhd kirsch_synth_pkg.vhd syn_fifo.vhd kirsch.vhd components.vhd kirsch_top.vhd" )

