PY_TB_VHDL = [ "string_pkg.vhd", "kirsch_unsynth_pkg.vhd", "kirsch_tb.vhd" ]
OPT_EFFORT_PHYS = 0
PY_DESIGN_VHDL = [ "mem.vhd", "kirsch.vhd" ]
USER_TOOL_FLAGS = 
PART = EP4SGX70HF35M3
DESIGN_ARCH = main
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/stratixiv
RUN_SHIM = True
SIM_TOOL = MODELSIM

ECE327 = /home/ece327
SH_TB_VHDL = string_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd
TB_ENTITY = kirsch_tb
GOAL_FREQ = 50
GOAL_PERIOD = 20
PRECISION_PART = EP4SGX70HF35M
RPT_DIR = RPT
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/stratixiv" ]
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/stratixiv }
LOGIC_SYNTH_TOOL = PRECISION_RTL
TB_ARCH = main
TCL_TB_VHDL = { string_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd }
GUI_FLAG = -shell
NUM_TIMING_PATHS = 5
PWR_TOOL = QUARTUS
INTERACTIVE_FLAG = False
BOARD = STRATIXIV
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = kirsch
FAMILY_SHORT = StratixIV
SH_DESIGN_VHDL = mem.vhd kirsch.vhd
ASIC = False
LC_FAMILY_SHORT = stratixiv
OPT_EFFORT = 0
GENERICS = {  }
LIB_VHDL = util.vhd, kirsch_synth_pkg.vhd
SH_LIB_VHDL = util.vhd kirsch_synth_pkg.vhd
USE_GUI = False
TB_VHDL = string_pkg.vhd, kirsch_unsynth_pkg.vhd, kirsch_tb.vhd
SIM_SCRIPT = kirsch_tb.sim
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/stratixiv
LOGIC_SYNTH_EXT = vhd
RPT_TDIR = RPT
FAMILY_LONG = Stratix IV
TCL_DESIGN_VHDL = { mem.vhd kirsch.vhd }
SPEED = 3
UWP = kirsch
OLD_DC_SHELL = False
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
TCL_LIB_VHDL = { util.vhd kirsch_synth_pkg.vhd }
DESIGN_VHDL = mem.vhd, kirsch.vhd
PY_LIB_VHDL = [ "util.vhd", "kirsch_synth_pkg.vhd" ]
